### PR TITLE
Refactor github actions

### PR DESCRIPTION
**Pull request by RadiumRocket**
# [projectCode-XXX: title-of-ticket](JIRA_url)

> Ticket code, title of the ticket and as a hyperlink, the corresponding JIRA link

## Type of change

> Exchange rate entered. The possible values ​​for this section are:
>
> - Feature (new feature of the server/application)
> - Bug Fix (problem solution in development environment)
> - Hot Fix (problem solution in production environment)
> - Environment Merge (merge branches to different environments)

## Description

> - Brief description of the changes introduced in this PR.
> - It must write what was changed, why it was changed and for what purpose.
> - It is recommended to describe it in points to facilitate understanding.

## Attachments

> Images or videos showing the behavior of what is introduced in the UI, necessary to facilitate the understanding and correction of the PR.
> In the event that what has been done cannot be visually detected (for example, work on the Backend), this section will remain empty.

## Change Procedure

> Elements to take into account when merging or reviewing the PR. For example:
> If the mergeo depends on another PR
> The priority of the mergeo of it
> What variables must be taken into account in order to review the PR

### CODE REVIEW

**Comment by RadiumRocket** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>a514109</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://frontend-template-jz55s0btq-radium-rocket.vercel.app'>https://frontend-template-jz55s0btq-radium-rocket.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/radium-rocket/frontend-template/5KFJw72fszUtJMdAnK3YPSTE898X'>https://vercel.com/radium-rocket/frontend-template/5KFJw72fszUtJMdAnK3YPSTE898X</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/RadiumRocket/frontend-template/actions/runs/3086180110)

**Comment by RadiumRocket** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>13b57bd</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://frontend-template-37.vercel.app'>https://frontend-template-37.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/radium-rocket/frontend-template/4t4BAzkW9dzCP9KwGFXec3JJHLuE'>https://vercel.com/radium-rocket/frontend-template/4t4BAzkW9dzCP9KwGFXec3JJHLuE</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/RadiumRocket/frontend-template/actions/runs/3086222905)

**Comment by RadiumRocket** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>5a815e0</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://frontend-template-ickjtfnmm-radium-rocket.vercel.app'>https://frontend-template-ickjtfnmm-radium-rocket.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/radium-rocket/frontend-template/FnccJ3rbvM8wk6UNfuSvmP6KUsBL'>https://vercel.com/radium-rocket/frontend-template/FnccJ3rbvM8wk6UNfuSvmP6KUsBL</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/RadiumRocket/frontend-template/actions/runs/3086526019)

**Comment by RadiumRocket** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>5da4120</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://frontend-template-m00rpg5ra-radium-rocket.vercel.app'>https://frontend-template-m00rpg5ra-radium-rocket.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/radium-rocket/frontend-template/6Xpu6aPAyTG3rBBNge9RArP6vm84'>https://vercel.com/radium-rocket/frontend-template/6Xpu6aPAyTG3rBBNge9RArP6vm84</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/RadiumRocket/frontend-template/actions/runs/3086545362)

**Comment by RadiumRocket** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>b4e66fe</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://frontend-template-du6nh633h-radium-rocket.vercel.app'>https://frontend-template-du6nh633h-radium-rocket.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/radium-rocket/frontend-template/81QiMnd3EaVgzbSvSsC8FBUjC5AU'>https://vercel.com/radium-rocket/frontend-template/81QiMnd3EaVgzbSvSsC8FBUjC5AU</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/RadiumRocket/frontend-template/actions/runs/3087107887)

**Comment by RadiumRocket** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>eeb7e23</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://frontend-template-ef34tjhbu-radium-rocket.vercel.app'>https://frontend-template-ef34tjhbu-radium-rocket.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/radium-rocket/frontend-template/AUrLp64jrWeNZfiWzWuVj1DXvBWr'>https://vercel.com/radium-rocket/frontend-template/AUrLp64jrWeNZfiWzWuVj1DXvBWr</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/RadiumRocket/frontend-template/actions/runs/3087123066)

**Comment by RadiumRocket** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>8533aea</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://frontend-template-2owc1jyyd-radium-rocket.vercel.app'>https://frontend-template-2owc1jyyd-radium-rocket.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/radium-rocket/frontend-template/HmSfjeWv9cznJk9ugFdek9g3Dkye'>https://vercel.com/radium-rocket/frontend-template/HmSfjeWv9cznJk9ugFdek9g3Dkye</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/RadiumRocket/frontend-template/actions/runs/3087131618)

**Comment by RadiumRocket** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>1ace19f</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://frontend-template-inovrhmyt-radium-rocket.vercel.app'>https://frontend-template-inovrhmyt-radium-rocket.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/radium-rocket/frontend-template/D5DdWdEuBx5DZxPebU7WkvGwJdXg'>https://vercel.com/radium-rocket/frontend-template/D5DdWdEuBx5DZxPebU7WkvGwJdXg</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/RadiumRocket/frontend-template/actions/runs/3087169322)

**Comment by RadiumRocket** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>1ace19f</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://frontend-template-5unqhqrc0-radium-rocket.vercel.app'>https://frontend-template-5unqhqrc0-radium-rocket.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/radium-rocket/frontend-template/9v5dCcuki4AGrWN5EMhnoEWGLk1s'>https://vercel.com/radium-rocket/frontend-template/9v5dCcuki4AGrWN5EMhnoEWGLk1s</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/RadiumRocket/frontend-template/actions/runs/3087169322)

**Comment by RadiumRocket** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>8043084</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://frontend-template-jmbak8cdm-radium-rocket.vercel.app'>https://frontend-template-jmbak8cdm-radium-rocket.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/radium-rocket/frontend-template/HZM9hh5sKjh3ofKcpWdwKHgSE6wk'>https://vercel.com/radium-rocket/frontend-template/HZM9hh5sKjh3ofKcpWdwKHgSE6wk</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/RadiumRocket/frontend-template/actions/runs/3087197096)

**Comment by RadiumRocket** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>550af4d</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://frontend-template-hl4xq8upv-radium-rocket.vercel.app'>https://frontend-template-hl4xq8upv-radium-rocket.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/radium-rocket/frontend-template/F3NVwm75qgDjzzvyuR2C37HQEksK'>https://vercel.com/radium-rocket/frontend-template/F3NVwm75qgDjzzvyuR2C37HQEksK</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/RadiumRocket/frontend-template/actions/runs/3087202185)

**Comment by RadiumRocket** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>af634c2</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://frontend-template-bqmd3d2tx-radium-rocket.vercel.app'>https://frontend-template-bqmd3d2tx-radium-rocket.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/radium-rocket/frontend-template/GMq6rwL6b8WjxYABshLvTwErjd5y'>https://vercel.com/radium-rocket/frontend-template/GMq6rwL6b8WjxYABshLvTwErjd5y</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/RadiumRocket/frontend-template/actions/runs/3087236632)

**Review by estefrare — APPROVED** [review]

**Pull request merged**
