### PR TITLE
FT: make a change to invoke workflow

### PR DESCRIPTION
**Pull request by RadiumRocket**
# [projectCode-XXX: title-of-ticket](JIRA_url)

> Ticket code, title of the ticket and as a hyperlink, the corresponding JIRA link

## Type of change

> Exchange rate entered. The possible values ​​for this section are:
>
> - Feature (new feature of the server/application)
> - Bug Fix (problem solution in development environment)
> - Hot Fix (problem solution in production environment)
> - Environment Merge (merge branches to different environments)

## Description

> - Brief description of the changes introduced in this PR.
> - It must write what was changed, why it was changed and for what purpose.
> - It is recommended to describe it in points to facilitate understanding.

## Attachments

> Images or videos showing the behavior of what is introduced in the UI, necessary to facilitate the understanding and correction of the PR.
> In the event that what has been done cannot be visually detected (for example, work on the Backend), this section will remain empty.

## Change Procedure

> Elements to take into account when merging or reviewing the PR. For example:
> If the mergeo depends on another PR
> The priority of the mergeo of it
> What variables must be taken into account in order to review the PR

### CODE REVIEW

**Comment by RadiumRocket** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>0603b73</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://frontend-template-h20y3eesg-radium-rocket.vercel.app'>https://frontend-template-h20y3eesg-radium-rocket.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/radium-rocket/frontend-template/Gctjm4gAqBCkpFAqME9Gud31Q5gw'>https://vercel.com/radium-rocket/frontend-template/Gctjm4gAqBCkpFAqME9Gud31Q5gw</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/RadiumRocket/frontend-template/actions/runs/3091678368)

**Comment by RadiumRocket** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>428ae5a</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://frontend-template-4jo9odt3d-radium-rocket.vercel.app'>https://frontend-template-4jo9odt3d-radium-rocket.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/radium-rocket/frontend-template/6AqqDwVR2mCGiXXc5D11DunAYuXX'>https://vercel.com/radium-rocket/frontend-template/6AqqDwVR2mCGiXXc5D11DunAYuXX</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/RadiumRocket/frontend-template/actions/runs/3091683319)

**Comment by RadiumRocket** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>8b99e75</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://frontend-template-btvzr531o-radium-rocket.vercel.app'>https://frontend-template-btvzr531o-radium-rocket.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/radium-rocket/frontend-template/EauuzBxnPFu1Vf9ciYBhxTaE9LKW'>https://vercel.com/radium-rocket/frontend-template/EauuzBxnPFu1Vf9ciYBhxTaE9LKW</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/RadiumRocket/frontend-template/actions/runs/3091706331)

**Review by estefrare — APPROVED** [review]

**Comment by RadiumRocket** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>53e3840</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://frontend-template-qveupvwg2-radium-rocket.vercel.app'>https://frontend-template-qveupvwg2-radium-rocket.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/radium-rocket/frontend-template/917PKb2bGJ6BUtfkBrSJCKqmiKA3'>https://vercel.com/radium-rocket/frontend-template/917PKb2bGJ6BUtfkBrSJCKqmiKA3</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/RadiumRocket/frontend-template/actions/runs/3091724800)

**Pull request merged**
